version: 2
jobs:
  build:
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker build -t ansible-ci:2.7.6 .
              docker login -u alopsing -p ${docker_hub_password}
              docker push alopsing/ansible-ci:2.7.6
            fi
