docker:
  - image: docker:17.05.0-ce-git
  - checkout
  - deploy:
    name: Push application Docker image
    command: |
      if [ "$ {CIRCLE_BRANCH}" == "master" ]; then
        docker build -t ansible:2.7.6 .
        docker login -u alopsing -p ${docker_hub_password}
        docker push alopsing/ansible:2.7.6
      fi
